version: '3'

services: 
  deber:
      container_name: deberdevops
      restart: always
      build: .
      ports:
       - "3000:4000"
      links:
       - mongodb
      volumes:
       - .:/usr/src/app
  mongodb:
      container_name: basededatos
      image: mongo
      ports: 
      - "27017:27017"
